.github/workflows/ecrbuild-all.yml

Jobs using `m-ubuntu-latest` were stalling.
Default runner in public repos is 4vCpu/16GB RAM (https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
`m-ubuntu` runner we were using for private repo is only 14Gb. Also we can't use it anymore, I think it's for private repos only? If you go to https://github.com/pubpub/platform/settings/actions/runners you see that no runners are even configured atm, which was probably why they were stalling.
See if CI completes

fix: use default runners instead of paid ones

---

core/app/c/[communitySlug]/pubs/PubHeader.tsx
core/app/components/forms/FormElement.tsx
core/app/components/pubs/CreatePubButton.tsx
core/app/components/pubs/PubEditor/PubEditor.tsx
core/app/components/pubs/PubEditor/PubEditorClient.tsx
core/app/components/pubs/PubEditor/actions.ts
core/app/components/pubs/UpdatePubButton.tsx

https://knowledgefutures.slack.com/archives/CMAQM0BNV/p1727286693619029
File upload was not working on form create. This fixes that by generating a pubId the file uploader can use when uploading files. Also has to remove a Suspense key which was causing the whole form to rerender when changing members or files

Create client side pubId to file upload can work

---

core/app/components/forms/FormElement.tsx

Closes https://github.com/pubpub/pubpub/issues/3178
https://github.com/pubpub/platform/pull/528 refactored the rendering of structural components to use `react-markdown` instead, but the components are actually saved as HTML so `react-markdown` just renders an escaped version of the html rather than what the html says to render. I restored what was originally there, though we should do a pass thru the app and sanitize all the places we put `TODO: sanitize`! Also, not sure if there was a particular reason it was changed to `Markdown` in that PR that I'm missing?
* Add a structural element to a form with markdown
* View the `fill` version of the form. the markdown should render as expected

Restore setting html to render rich text in forms

---

core/prisma/migrations/20240923161145_add_null_core_schema_type_and_make_pubvalues_unique_constraint_not_null_unique/migration.sql

https://knowledgefutures.slack.com/archives/CMAQM0BNV/p1727361690973769
I used `NULLS NOT DISTINCT` which is only available in pg15, not realizing we are only on pg14 in prod!

Fix `NULLS` migration for pg14

---

core/app/components/pubs/PubEditor/actions.ts
core/app/components/pubs/PubEditor/helpers.ts

#673 
The query we use to update pub values uses the presence of an `id` on the values we insert to determine whether they should be new rows or updates to existing rows. Because of an error in the prior query, we were not setting the id on every value, which this PR fixes.
This also fixes a bug where we were creating invalid dates while making the default values for the pub create form.
1. Update a pub, it should succeed!
2. Create a dateTime field and add it to a pub type
3. On the pubs page, open the create pub form and select the type with the dateTime field
4. Make sure you can create a pub of that type

Fix pub creation and editing

---

core/lib/server/pub.ts

Quick follow up to https://github.com/pubpub/platform/pull/676 which replaced the create pub function, but neglected to keep the ability to specify a client side id (doh!)
Needed for https://github.com/pubpub/platform/pull/657 to keep working properly
* Create a field type of FileUpload
* Add this field type to a pub type
* Create a pub of this pub type and upload a file. In the network tab, you can inspect for what path this file is being uploaded to. Make a note of the pub Id
* Submit the create pub form
* The created pub's id should match the pub id that the file upload went up to (this is currently broken after https://github.com/pubpub/platform/pull/676!)

Restore id to creating pub

---

.github/workflows/deploy-template.yml
.github/workflows/ecrbuild-all.yml

- **fix: restore building the base image, as we need it for migrations**
- **feat: make ECS deploy task wait until service is stable**
Core was not deploying correctly
For the integration tests PR, i commented out the building of the base image (up until the `monorepo` step in `Dockerfile`), because I thought it was unnecessary.
Turns out we use it for migrations, and core needs it to be able to run. Thus, it is restored.
I added the `wait-for-service-stability: true` flag on the ECS deploy task, which should hopefully fail CD (show us an x) if the service does not start succesfully in the future.
1. Make sure base image builds and is pushed during CI.
2. Send it.

fix: restore base image build on pr/main 

---

core/app/components/forms/elements/ConfidenceElement.tsx
packages/sdk/src/react/generateFormFields.tsx
packages/ui/src/customRenderers/confidence/confidence.tsx

Closes https://github.com/pubpub/platform/issues/681
I don't know why this didn't happen before, but it appears that we need to be careful not to pass `onChange` to `Confidence` if we are passing `onValueChange`. This PR just makes sure we don't pass `onChange` along with `onValueChange` since that results in a bad set state
See repro steps in https://github.com/pubpub/platform/issues/681 only the page shouldn't crash anymore!
https://github.com/user-attachments/assets/886044f5-9de9-4879-b8a1-748918e9084b
~~There is also a forwardRef error which I was able to fix but not without being TS compliant, so I'm still looking into it...~~
Fixed! There was a forwardRef error showing up in the console which was a result of dynamically importing the slider component. Fixed using the strategy …

Fix onChange of slider component

---

core/app/c/(public)/[communitySlug]/public/forms/[formSlug]/fill/page.tsx

https://kfg.sentry.io/issues/5947937548/?referrer=slack&notification_uuid=1cd3906b-24f1-4645-97ce-
afcbfd8b50ad&alert_rule_id=14700264&alert_type=issue
https://kfg.sentry.io/issues/5947682287/?referrer=slack&notification_uuid=bdeb0e60-f32f-4430-8042-336074f9fbbd&alert_rule_id=14700264&alert_type=issue
This is just a quick fix to stop the fill page from crashing. In the future we'll provide feedback on the fill page to stop people from saving invalid markdown in the first place
Add a paragraph element to a form, then set it's contents to a directive syntax error such as a bare `:link` 
Visit the fill page and make sure you don't see an error

Return content unchanged when structural elements contain invalid markdown

---

.github/workflows/e2e.yml

Call `exec` from `e2e.yml` so that we use the installed version of playwright in `node_modules`. To try not to get an error where we are using two different playwright versions!

Try using exec when playwright installs browser

---

core/app/c/(public)/[communitySlug]/public/forms/[formSlug]/fill/page.tsx
core/app/c/[communitySlug]/forms/[formSlug]/edit/page.tsx
core/lib/server/render/pub/renderMarkdownWithPub.ts

Closes https://github.com/pubpub/platform/issues/705
On form create, there is no pub ID. Before, the form just wouldn't render any structural markdown. Now, it renders it, but it won't be able to handle the directives that reference a pub.
* Create a form with structural paragraph and put markdown in it
* Visit the form's fill page i.e. http://localhost:3000/c/croccroc/public/forms/review/fill
* The markdown should render
* The markdown should also render if you pass a pubId param
* Adding a directive like `:link[view]{field="croccroc:url"}` should work in the URL with the pub id, but should render nothing in the URL without the pub id.
Without pub ID
With pub ID

Fix markdown rendering when form is creating a pub

---

.github/workflows/on_main.yml

- **dev: make e2e tests run on promotion to main**
- **fix: make deploy wait for e2e, duh**
We should probably be good children and eat our vegetables and just run e2e tests on promotion to main even though we require you to run be up to speed with main anyway.

dev: run e2e tests before deploying

---

core/app/c/[communitySlug]/forms/[formSlug]/edit/page.tsx
core/app/components/FormBuilder/ElementPanel/InputComponentConfigurationForm.tsx
core/app/components/FormBuilder/ElementPanel/StructuralElementConfigurationForm.tsx
core/app/components/FormBuilder/FormBuilder.tsx
core/app/components/FormBuilder/FormBuilderContext.tsx
core/app/components/FormBuilder/SaveFormButton.tsx

Resolves #445 
This PR changes the form builder to prompt the user (in a blocking manner) about unsaved changes when navigation occurs.
The top-level form builder, structural element editor, and input component editor all received a `useUnsavedChangesWarning` hook call that triggers the default browser unsaved changes prompt when the form state is dirty (modified).
This means that the warning prompt is triggered:
- if you modify a child (structural/input) form without saving the changes
- if you modify a child (structural/input) form and save the changes, but do not save the form
- if you modify the form itself (e.g. add/delete/reorder elements) without saving it
The "save" button within the structural element editor, input component editor, and top-level form builder were changed to …

Add unsaved changes warning to form builder

---

core/app/c/(public)/[communitySlug]/public/forms/[formSlug]/fill/ExternalFormWrapper.tsx
core/app/c/(public)/[communitySlug]/public/forms/[formSlug]/fill/page.tsx
core/app/c/[communitySlug]/forms/[formSlug]/edit/page.tsx
core/app/components/FormBuilder/ElementPanel/InputComponentConfigurationForm.tsx
core/app/components/FormBuilder/ElementPanel/SelectAccess.tsx
core/app/components/FormBuilder/ElementPanel/StructuralElementConfigurationForm.tsx
core/app/components/FormBuilder/FormBuilder.tsx
core/app/components/FormBuilder/FormBuilderContext.tsx
core/app/components/FormBuilder/SaveFormButton.tsx
packages/ui/src/hooks/index.ts
packages/ui/src/hooks/useUnsavedChangesWarning.tsx

Kind of related to #692. These changes would at least notify users if they would lose progress.
Also partially related to #445, in that it introduces a general-purpose React hook for warning about unsaved changes. The general strategy here can be used on the form builder as well.
This PR changes the external form fill page to notify the user about unsaved changes when navigating. It uses the standard `beforeunload` method of notifying the user in a blocking manner, giving them the opportunity to cancel navigation.
The PR accounts for autosave by clearing the "dirty" flag from the form after an auto-save occurs.
I also change the form to only submit _changed_ values which can potentially make Pub editing w/ forms a bit snappier.
1. Open a form fill page.
2. Change a value. Attempt to …

Add unsaved changes warning to form

---

core/app/c/[communitySlug]/types/TypeBlock.tsx
core/app/components/FormBuilder/ElementPanel/ComponentConfig/MultivalueInput.tsx
core/app/components/FormBuilder/ElementPanel/ComponentConfig/index.tsx
core/app/components/FormBuilder/ElementPanel/InputComponentConfigurationForm.tsx
core/app/components/forms/FormElement.tsx
core/app/components/forms/elements/MultivalueInputElement.tsx
core/app/components/pubs/PubEditor/PubEditorClient.tsx
core/playwright/externalFormCreatePub.spec.ts
core/playwright/fixtures/pubtype-page.ts
core/playwright/pub.spec.ts
core/prisma/migrations/20241016174257_add_multivalue_input_to_input_component_enum/migration.sql
core/prisma/schema.prisma
packages/db/src/public/InputComponent.ts
packages/db/src/public/PublicSchema.ts
packages/schemas/src/schemaComponents.ts
packages/ui/src/multivalue-input.tsx

Closes https://github.com/pubpub/platform/issues/706
Adds the multivalue input component to various parts of the app:
* Form builder for `StringArray` and `NumericArray` fields
* Form fill page if the multivalue input component was chosen
* The pub update/create form
* Add a pub field that is either of type `StringArray` or `NumericArray`
* Add to a form and select the multivalue input field. You should be able to add a label/description if you want.
* Check that the field renders and works as you'd expect it to in the form fill page
* Add the same field to a pub type
* Try to create/edit a pub of this type. You should be able to use the multivalue input component for the field you added
With field disabled

Multivalue input in form builder, pub editor, and form fill page

---

Dockerfile

Static assets not properly resolved for integrations because they were copied to the wrong place in the dockerfile.
Send it.

fix: copy integration data to the correct folder

---

core/app/c/[communitySlug]/SideNav.tsx

Resolves #633
Just makes uses `isAdmin` rather than `isSuperAdmin` for the `stages/manage` page.
1. Login as a regular admin (new@pubpub.org, `pubpub-new`)
2. See the `Stage Editor` in the sidebar to the left
I will fix the highlighting in a follow up PR, have one semi ready where I introduce shadcn's new sidebar component.

fix: allow admins to access stage editor

---

core/prisma/migrations/20241105184158_copy_membership_data/migration.sql

Failed migration from #755 
The previous migration failed to apply because the tables it was copying didn't contain the same number of columns as the target tables. In cases where the source data has fewer columns than the target table, Postgres defaults to inserting the columns in order, leaving the extra columns at the end null.  So for the first query, because there's no `members."memberGroup"` column, the returned data ended up partially in the wrong columns. To fix that, we just explicitly specify the target table columns that we want to insert data into as well.
Mark the old migration as failed, then deploy this ¯\\\_(ツ)\_/¯

Specify target columns in migration

---

core/prisma/migrations/20241105184158_copy_membership_data/migration.sql

Another error in the migration from #755 
There's no error in the logs because [prisma hides migration errors if you use a transaction](https://github.com/prisma/prisma/issues/15295). But running the sql against prod manually with `psql` showed an error:
```
/usr/src/app/core # psql -f prisma/migrations/20241105184158_copy_membership_data/migration.sql
BEGIN
INSERT 0 126
psql:prisma/migrations/20241105184158_copy_membership_data/migration.sql:12: ERROR:  duplicate key value violates unique constraint "form_memberships_formId_userId_key"
DETAIL:  Key ("formId", "userId")=(d6aa0d8a-25ce-4ff5-b2ac-0bc6d3b91311, 9fb919ac-c317-414e-a8b9-f4d3d233b8c6) already exists.
ROLLBACK
```
Much like the copied memberships, there will already be some form_memberships from users who were invited to forms …

Add on conflict clause to form_memberships copy

---

core/.env.development
core/docs/load-testing.md
core/load-test.yaml
core/package.json

#744
This PR introduces an npm script to the `core` package that executes a simple load test against our production environment at https://app.pubpub.org. The load test is a placeholder as it only generates traffic to "lightweight" public pages: `/login` and `/forgot`.
Follow the instructions in the [load test readme](core/docs/load-testing.md). Artillery Cloud API credentials are not necessary to run the tests, the results just won't be reported to Artillery Cloud.

Simple load test script

---

core/load-test-flows.ts
core/load-test.yaml
core/package.json
core/playwright/externalFormCreatePub.spec.ts
core/playwright/externalFormInvite.spec.ts
core/playwright/externalFormWithPubId.spec.ts
core/playwright/fields.spec.ts
core/playwright/fixtures/login-page.ts
core/playwright/formBuilder.spec.ts
core/playwright/helpers.ts
core/playwright/login.flows.ts
core/playwright/login.spec.ts
core/playwright/member.spec.ts
core/playwright/pub.spec.ts
pnpm-lock.yaml

Resolves #745
This PR extracts a function used by the login-related end-to-end tests for reuse as a load testing virtual user scenario.
While technically this does not reuse a complete end-to-end test for load testing, it does confirm that we can use playwright as a load test engine and introduces a pattern that enables us to share playwright tests between our end-to-end and load test suites.
I have also simplified the load test configuration for now just to make the config file as easy to understand as possible!
- Run the tests using the instructions in the [load testing readme](https://github.com/pubpub/platform/blob/main/core/docs/load-testing.md)
- Watch the tests fail!
- Optionally, remove the `phases` property from the `load-test.yaml` file. Run the tests and watch them pass!

use login playwright flow as load test

---

core/app/c/[communitySlug]/pubs/PubList.tsx
core/app/c/[communitySlug]/pubs/page.tsx
core/app/components/Pagination.tsx
core/lib/server/pub.ts
core/prisma/exampleCommunitySeeds/arcadia.ts
core/prisma/seed.ts
packages/ui/src/pagination.tsx

- **feat: add very basic pagination to pubs list**
- **fix: orderby updatedat even though that doesn't really work like you think it would**
Resolves #778. Technically the `updatedAt` does not really work as you think it would, as it only sorts by the Pubs `updatedAt`, which rarely changes. I created #809 to do this in a more intuitive way.
Adds pagination to the Pubs page by creating a new component called `PaginatedPubsList`, which does the same as `PubsList`, just paginated.
Note: this also encroaches a bit on #801, as I didn't want to re add creating the token logic to this PubList if it would get taken out anyway.
I can incorporate #801 into this PR quite easily as well if needed. 
- Initially I also wanted to make this page use `getPubsWithRelatedValuesAndChildren` instead, but that …

feat: paginate  pubs page

---

core/app/api/v0/c/[communitySlug]/site/[...ts-rest]/route.ts
core/lib/authorization/capabilities.ts
core/lib/server/apiAccessTokens.ts
core/lib/server/errors.ts
core/lib/server/pub.db.test.ts
core/lib/server/pub.ts
core/prisma/exampleCommunitySeeds/arcadia.ts
core/prisma/seed/seedCommunity.db.test.ts
core/prisma/seed/seedCommunity.ts
packages/contracts/src/resources/site.ts

- **feat: add rough sketch for new pub api routes**
- **feat: add basic way to update and delete pub**
- **fix: refine updating and removing slightly such that they work**
- **feat: make upsert relation work sort of**
- **chore: small cleanup**
- **fix: move processedpubtype to contracts, replace output schema with processedpubschema for all pub operations**
- **refactor: do not make update functions check for pub existence, move resp to caller**
- **refactor: make communityId mandatory for getPubsWithRelatedValuesAndChildren**
- **fix: return full pub from relation routes**
- **chore: add descriptions to existing relation endpoints**
- **refactor: change the output type of createPubRecursiveNew to be ProcessedPub, to match what is returned by getPubWithChildren etc**
- **chore: clean up …

feat: add relation manipulation to api, and update get routes to return relations as well

---

infrastructure/terraform/environments/stevie/.terraform.lock.hcl
infrastructure/terraform/modules/deployment/main.tf

Resolves #806 
Output of `mask tf plan -n stevie`:
```tf
Terraform will perform the following actions:
<= data "aws_ecs_task_definition" "this" {
+ arn                  = (known after apply)
+ arn_without_revision = (known after apply)
+ execution_role_arn   = (known after apply)
+ family               = (known after apply)
+ id                   = (known after apply)
+ network_mode         = (known after apply)
+ revision             = (known after apply)
+ status               = (known after apply)
+ task_definition      = "stevie-core"
+ task_role_arn        = (known after apply)
}
+/- resource "aws_ecs_task_definition" "this" {
~ arn                      = "arn:aws:ecs:us-east-1:246372085946:task-definition/stevie-core:142" -> (known after apply)
~ arn_without_revision     = …
```

Double CPU and memory of prod core ECS task

---

core/app/c/[communitySlug]/forms/[formSlug]/edit/page.tsx
core/app/c/[communitySlug]/forms/getFormTableColumns.tsx
core/app/c/[communitySlug]/forms/page.tsx
core/prisma/migrations/20241203035210_add_default_forms/migration.sql
core/prisma/schema.dbml
core/prisma/schema.prisma
packages/db/src/public/Forms.ts
packages/db/src/table-names.ts

#781 
- Adds default column to database table
- Adds notice to form builder header
- Adds default column to table on forms page
I tested by manually setting isDefault to true for a form in the database. You could do that too, or just trust me :)
I went with `isDefault` for minor convenience since `default` is a reserved word. Also I'm very unsure about the placement of the text on the form builder page and the "Yes"/"No" in the table. Let me know if you have any suggestions!

Add default column to forms

---

core/app/c/[communitySlug]/pubs/[pubId]/components/RelatedPubsTable.tsx
core/app/c/[communitySlug]/pubs/[pubId]/components/getPubChildrenTableColumns.tsx
core/app/c/[communitySlug]/pubs/[pubId]/page.tsx

Closes https://github.com/pubpub/platform/issues/777
Related pubs can now be seen on pub detail pages.
Visit the journal article called "Identification of capsid-like proteins in venomous and parasitic animals" in the Arcadia seed community. You should be able to see its related pubs, grouped by relationship type.
No "actions" or "member fields" rendering yet since those would require more queries ([convo here](https://knowledgefutures.slack.com/archives/CMAQM0BNV/p1732722697668169?thread_ts=1732649416.238439&cid=CMAQM0BNV))

Related pubs table

---

core/actions/_lib/runActionInstance.ts
core/actions/types.ts
core/app/c/[communitySlug]/forms/actions.ts
core/app/c/[communitySlug]/types/actions.ts
core/kysely/errors.ts
core/lib/server/form.ts
core/lib/server/render/pub/renderMarkdownWithPub.ts
core/lib/server/render/pub/renderWithPubUtils.ts
core/prisma/migrations/20241205192106_unique_pub_type_names/migration.sql
core/prisma/migrations/20241205231134_backfill_default_forms/migration.sql
core/prisma/schema.dbml
core/prisma/schema.prisma
core/prisma/seed/seedCommunity.ts

Resolves #782 
Resolves #817 
- Adds a pubtitle directive: `:value{field="title"}` which uses the old pubtitle logic for now
- Adds a unique constraint to prevent duplicate named pub types. This makes it less likely that we'll encounter unique constraint errors when creating the default form
- Updates the form insert query to add a paragraph element with the new title directive as the first form element on new forms
- Factors out and uses the form insert query to automatically create a default form whenever a new pub type is created
- Adds a migration that replicates our default form creation logic for all the existing pub types
Since the migration occurs before the seed script runs, try resetting your db (or not), then manually running the migration with psql or whatever db client you …

Add default form when creating pub type

---

core/app/c/[communitySlug]/CommunitySwitcher.tsx
core/app/c/[communitySlug]/SideNav.tsx
core/app/c/[communitySlug]/layout.tsx
core/lib/server/community.ts
core/playwright/externalFormInvite.spec.ts

Resolves #807 
Previously when a user visited a community page (`/c/*`) we would return 404 if they were a contributor of that community. Now we send them to `/settings`, which should be a better experience since that page is always usable by any user. We also now handle the case where you are not a member of the community at all.
This should also slightly improve the UX in #743 since those users will be sent to the settings page instead of our nonexistent 404 page. The links to communities on that page will just redirect them back to settings for now, but once we implement the rest of our auth checks, we can remove that. 
There's an e2e test but to test manually:
- As Jill Admin:
- Visit the community members page
- Remove none@pubpub.org
- Logout
- Login as `none@pubpub.org` / …

Redirect non-members to /settings 

---

core/prisma/seed/seedCommunity.ts

Seeded forms only had the title paragraph element, but no input elements because they were created before any fields were added to the pub type

Add fields to pub type before default form in seed script

---

core/app/(user)/communities/page.tsx
core/app/(user)/login/page.tsx
core/app/(user)/settings/page.tsx
core/app/c/[communitySlug]/layout.tsx
core/app/page.tsx

Non-logged in users were always being sent to `https://app.pubpub.org/settings` which returns the next default error page - a significantly worse experience than before. Now they should get redirected to /login with the appropriate redirect param.
I also deleted the lucia migration notice because it's been a while!
I made sure to use `getPageLoginData` anywhere that we'd like a login redirect to happen for unauthenticated users!
Visit localhost:3000/c/unjournal/stages locally without being logged in. You should be redirected to the login page

Make login redirect work again and remove login notice

---

core/app/c/(public)/[communitySlug]/public/forms/[formSlug]/fill/page.tsx
core/app/c/[communitySlug]/fields/actions.ts
core/app/c/[communitySlug]/stages/components/Assign.tsx
core/app/c/[communitySlug]/stages/components/Move.tsx
core/app/c/[communitySlug]/stages/components/lib/actions.ts
core/app/c/[communitySlug]/stages/manage/actions.ts
core/app/c/[communitySlug]/stages/manage/components/panel/actionsTab/StagePanelActionEditor.tsx
core/app/c/[communitySlug]/stages/manage/components/panel/actionsTab/StagePanelActions.tsx
core/app/c/[communitySlug]/stages/manage/components/panel/actionsTab/StagePanelRule.tsx
core/app/c/[communitySlug]/stages/manage/components/panel/actionsTab/StagePanelRuleCreator.tsx
core/app/c/[communitySlug]/stages/manage/components/panel/actionsTab/StagePanelRules.tsx
core/app/c/[communitySlug]/types/actions.ts
core/app/components/ActionUI/ActionConfigForm.tsx
core/app/components/ActionUI/ActionConfigFormWrapper.tsx
core/app/components/FormBuilder/actions.ts
core/app/components/forms/actions.ts
core/app/components/pubs/PubEditor/PubEditor.tsx
core/app/components/pubs/PubEditor/PubEditorClient.tsx
core/app/components/pubs/PubEditor/actions.db.test.ts
core/app/components/pubs/PubEditor/actions.ts
core/lib/__tests__/utils.ts
core/lib/server/errors.ts

Closes https://github.com/pubpub/platform/issues/758
All actions should now at the minimum do an authentication check that the user is logged in. 
I added authorization checks too where I could, though please check my assumptions! There were some I was not sure about, namely:
* Actions
* Rules
* Move constraints
I also haven't added the ones to the form builder yet since `userCan` does not cover the form memberships table yet, and I wasn't sure if that had to be specced out more or if there was another ticket for it?
Honestly I'm not sure the best way to test it—probably make users of different roles and try out the actions? I wrote a few unit tests, and the "Inviting a new user to fill out a form" E2E test was good for testing a new user who only had access to a form.

Secure server actions

---

core/lib/server/pub.ts
core/lib/server/validateFields.ts

- **fix: throw clearer errors on validation error**
- **fix: allow you to use dates in api**
Resolves #837
When passing pubfields through `validatePubFields`, i add a manual check for date fields and hydrate them.
I also made validation errors slightly more clear.
1. Send an api request like
```
POST /api/v0/c/arcadia-research/site/pubs
PREFER return=representation
{ 
"pubTypeId": <find a pubtype>,
"values": { "arcadia-research:created-at": "2012-07-09" }
}
```
You should be able to do it!
Ideally also test for `PATCH /pubs` and `PUT/PATCH pubs/relations`, but they all use the same function so should work.

fix: allow updates to DateTime CoreSchemaType values through the API

---

core/lib/server/pub.db.test.ts
core/lib/server/pub.ts
core/prisma/exampleCommunitySeeds/arcadia.ts

- **fix: make arcadiaseed accesstoken correct**
- **fix: do not error if no pubvalues are deleted**
`PUT pubs/relations` route would throw if no values existed beforehand, bc it would try remove pubvalues and then manually insert them into `pub_value_history`. there were no safeguards if there were no pubvalues to insert though, so it would try to `db.insertInto('pub_values_history').values([])`, which errors.
1. Run test
2. Ideally try to `PUT` a relation but this has some haste, so just wing it.

hotfix: allow deleting empty pubvalues

---

core/app/c/[communitySlug]/types/FieldSelect.tsx
core/app/c/[communitySlug]/types/TypeBlock.tsx
core/app/c/[communitySlug]/types/TypeEditor.tsx
core/app/c/[communitySlug]/types/page.tsx
core/app/c/[communitySlug]/types/utils.ts
core/playwright/externalFormInvite.spec.ts
core/playwright/fields.spec.ts
core/playwright/fixtures/fields-page.ts
core/playwright/fixtures/pub-types-page.ts
core/playwright/pubType.spec.ts
packages/ui/src/pubFields/PubFieldContext.tsx

- **fix: fetch relations when trying to add pubfields**
- **fix: add pubtype page tests**
- **fix: add test for checking whether yuo can designate field as title**
Allow users to add relation field types to pub type
We just weren't fetching the relationships on the PubTypes page, so i made it do that.
I also added some specific tests for pubtype creation.
In addition: you are not able to set relationship fields as the title. we should probably prevent this somewhere else too, but i'm too lazy to figure that out rn.
1. Create a relation field of SchemaType string
2. Create a pub type, add that relationship field to it.
3. Observe you cannot set it as the title
4. Tada

fix: allow adding relation fields to pubtype

---

core/lib/server/pub-trigger.db.test.ts
core/prisma/migrations/20241205152006_add_title_field/migration.sql
core/prisma/migrations/20241219131700_fix_title_update_trigger/migration.sql

- **fix: add working test that will show the unwanted behavior**
- **fix: correctly update the title if a non-pubtitle is updated**
- **fix: create a new migration instead of updating old one**
- **fix: update existing test instead of adding new test**
When updating a non-title value on a pub, it's `title` would get set to null!
@3mcd  identified this as a problem while working on #833 
I missed this because a test was not behaving properly for some reason.
Basically, because i wanted to be efficient and update the `updatedAt` and `title` on query, I used a `LEFT JOIN` here in the update query (bc i wanted to update the `updatedAt` even if no title update was necessary)
https://github.com/pubpub/platform/blob/a57197798f56fc5af66b6181af8fe6f9a2f803ca/core/prisma/migrations/20241205152006_ad …

fix: do not set title to null if a non-title value is updated

---

core/actions/_lib/runActionInstance.ts
core/actions/email/run.ts
core/actions/http/run.ts
core/actions/pushToV6/run.ts
core/actions/types.ts
core/lib/fields/utils.ts
core/lib/server/pub.ts
core/lib/server/render/pub/renderMarkdownWithPub.ts
core/lib/server/render/pub/renderWithPubUtils.ts
core/prisma/exampleCommunitySeeds/croccroc.ts

- **fix: make actions use correct types**
- **feat: make hydratePubValues more resuable**
- **feat: hydrate pubvalues before running action**
Resolves #760 
Also resolves another issue: bc of #823  the values that were passed to pubs changed, but the type did not change, probably breaking a bunch of actions unknowingly,
this fixes it.
Specifically i changed `runActionInstance` to fetch pubs like so
https://github.com/pubpub/platform/blob/cd32e0be1ac268b1f23b5fce4d623038854b5a3b/core/actions/_lib/runActionInstance.ts#L40-L46
but because of this `any` cast here `pubs.values` did not throw an error!
https://github.com/pubpub/platform/blob/cd32e0be1ac268b1f23b5fce4d623038854b5a3b/core/actions/_lib/runActionInstance.ts#L180-L187
extremely dangerous, bc in eg `renderMarkdownWithPub` …

fix: render dates properly and unbreak actions

---

api.http.h
core/.env.development
core/actions/datacite/run.ts
infrastructure/terraform.tfstate

There is still a discrepancy between dev and prod. Pub values with a `DateTime` schema are `Date`s in prod and strings in dev. This is causing the DataCite action to fail with the error `"The pub is missing a value corresponding to the configured publication date field override."`. This is a temporary fix to get the action working.

use string or date as publication date in datacite action

---

core/app/c/[communitySlug]/pubs/[pubId]/components/PubValues.tsx

https://kfg.sentry.io/issues/6174244816/events/503971d6e0204d8896c8ff28536ce098/
#867 changed how we render datetime fields on the pub page, which throws errors with some of the existing date values. This PR tests that the date value is parsed correctly before attempting to render it.

Test date fields before rendering on pub page

---

core/actions/googleDriveImport/formatDriveData.ts
core/actions/googleDriveImport/run.ts

Fixes three errors:
1. Where we would send a bad query if a legacy pub had no discussions.
2. Where we assumed a discussion always had a `comment.author`, but in cases with anonymous comments it has a `comment.commenter`.
3. We were passing in an undefined ORCID url even if the user didn't have an ORCID
- Import a pub with no discussions and make sure versions show up
- Import a pub with discussions and make sure they show up
- Repeat both and make sure both work as expected.
- Import a pub with anonymous `comment.commenter` discussions.
- Make sure it loads
- Make sure any users with ORCIDs and avatars have them passed in

Fix: pubs with no discussions

---

core/actions/googleDriveImport/formatDriveData.ts

Passing empty string instead of null caused validation errors where a non-string type was expected (e.g. a URL). This fixes that.

pass null instead of empty string to avoid validation errors

---

core/instrumentation.onRequestError.ts
core/instrumentation.ts

Previously, whenever an uncaptured error was thrown in a deeply nested server component (ie not at the top level of a page or layout), sentry would report this mysterious error in prod
`An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of...`
The above vague error was due to some Next limitation (https://github.com/getsentry/sentry-javascript/issues/14164#issuecomment-2454289406).
I believe the Next team worked with Sentry to fix this, by exposing a `onRequestError` export in `instumentation.ts`.
By setting that, Sentry is now able to properly report the error.
1. On `main`, or the base of this …

dev (next 15|3): add onRequestError which allows sentry capture of deep server component errors 

---

core/app/c/(public)/[communitySlug]/public/forms/[formSlug]/fill/page.tsx

N/A
Fixes a regression where invited members cannot view forms because they are unable to view the edited pub's parent pub.
On the Unjournal community,
1. Invite a (non-admin, non-superadmin) member to fill a pub via the email action
2. Open the form link in the email
3. The form fill page should load properly

fix: imply view permission to parent pub in form fill page

---

core/app/c/[communitySlug]/stages/manage/components/panel/StagePanelPubs.tsx

Quick fix to get the Pubs panel on the stage management page working again.

fix: missing await

---

core/app/c/[communitySlug]/stages/components/StageList.tsx
core/lib/stages.test.ts
core/lib/stages.ts
core/package.json
pnpm-lock.yaml

Resolves https://github.com/pubpub/platform/issues/888 and fixes the bug that led to reverting in #917
I added one new condition to the body of the loop to prevent infinite loops when the graph has a cycle. I've also added a 500ms timeout to the sorting function after which it just returns the deduped but unsorted stage list, in case there are other bugs and to make sure the app behaves reasonably with communities that have an unreasonable number of stages.

Use breadth first flattening order for stages (take 2)

---

core/actions/googleDriveImport/run.ts

Previously, no new version would be created if there wasn't already a version from the legacy migration. This fixes that.
If there's no existing version, it creates one from the existing HTML.
Tested with brand new pub and also with a legacy pub, and both seem to work.

Make first new versions when there's no migrated version

---

Dockerfile

The most recent ECS task deployment failed because the containers running our new node version don't seem to be able to run prisma migrate because they're missing openssl. See these logs
https://us-east-1.console.aws.amazon.com/ecs/v2/clusters/stevie-ecs-cluster-production/services/stevie-core/tasks/3813ad323b9d400086b5bc0d1181e8e7/logs?region=us-east-1
It turns out this is because moving from the image tag `node:20.17.0-alpine` to `node:22.13.1-alpine` also moved us from alpine `3.20.3` to `3.21.2`, which opens us up to [this prisma issue](https://github.com/prisma/prisma/issues/25817#issuecomment-2538544254) because libssl is installed in a different directory. We can probably also fix this by upgrading prisma now, but we should pin the underlying OS version anyways.
See if the …

Explicitly specify alpine version in docker image

---

core/actions/email/run.ts
core/actions/googleDriveImport/getGDriveFiles.ts
core/lib/env/env.mjs
core/lib/server/email.tsx
core/lib/server/mailgun.ts
self-host/README.md

- **feat: allow different email providers to be used when self-hosting, or allow users to disable email**
- **fix: handle errors and fix types**
Partially #954 
> [!Note]
> I will base the other self host prs on this one, but that does not mean we necessarily need to merge it!
> If for some reason we do not want to allow users to use different email providers  (?)
This allows users to pick a different email provider somewhat easily.
Adds some documentation and presets on how to use different email providers with platfrom.
Additionally, this makes the `MAILGUN_` env vars optional for self hosting. This will then only throw an error when you try to use the email client.
I don't want users to NEED to configure an email client. They should probably, but it should be possible to run one …

(self host 1/?): allow users to configure their own email service 

---

core/actions/_lib/runActionInstance.db.test.ts
core/app/api/v0/c/[communitySlug]/site/[...ts-rest]/route.ts
core/app/components/pubs/PubEditor/actions.ts
core/lib/__tests__/globalSetup.ts
core/lib/__tests__/live.db.test.ts
core/lib/__tests__/matchers.ts
core/lib/server/pub-capabilities.db.test.ts
core/lib/server/pub-op.db.test.ts
core/lib/server/pub-op.ts
core/lib/server/pub-trigger.db.test.ts
core/lib/server/pub.db.test.ts
core/lib/server/pub.fts.db.test.ts
core/lib/server/pub.sort.db.test.ts
core/lib/server/pub.ts
core/lib/server/pubFields.ts
core/lib/server/vitest.d.ts
core/prisma/seed/createSeed.ts
core/prisma/seed/seedCommunity.ts
core/vitest.config.mts
packages/schemas/package.json
packages/utils/package.json
packages/utils/src/uuid.ts

Adds a new PubOp system for creating, updating and managing relationships between Pubs using a fluent-like API/
> [!NOTE]
> This PR is an RFC! Meaning I'm totally happy not merging it!
> I'm more interested in your general thoughts on this approach, please nitpick it to hell!
This PR introduces a new `PubOp` system that provides a fluent, builder-style API for managing Pub operations. The system handles complex scenarios like creating multiple related pubs, managing nested relationships, and handling pub value updates in a single transaction.
The API follows a builder pattern, allowing for chaining operations:
```ts
const pub = await PubOp.create({
communityId: community.id,
pubTypeId: pubType.id,
lastModifiedBy: createLastModifiedBy({ userId: user.id }),
})
.set('title', 'My Pub') …
```

RFC: pubOp for creating and updating pubs more easily

---

core/app/c/[communitySlug]/pubs/[pubId]/edit/page.tsx
core/app/c/[communitySlug]/pubs/create/page.tsx
core/playwright/pub.spec.ts

Resolves #962 
Quick fix to make the pub create/edit forms a bit wider.
1. Open the pub create and edit forms and observe that they are now wider!

fix: pub create/edit form grow to container

---

.github/dependabot.yml
.vscode/extensions.json

- **dev: add dependabot**
- **dev: add yaml extension suggestion**
Dependencies going out of date and being annoying to update.
Adds a `dependabot.yml` with some relatively arbitrary settings.
`dependabot` recently [added support for `pnpm` workspace catalogs](https://github.blog/changelog/2025-02-04-dependabot-now-supports-pnpm-workspace-catalogs-ga/) which we we recently introduced. This means we can use it now, as our most important dependncies are managed in `workspaces.yml`.
In case you are unaware of what `dependabot` is: basically a bot that puts up PRs updating dependencies that have gone out of date. 
Given that we now have a reasonably robust test-suite, i feel relatively comfortable merging in patch/minor version updates if they pass our tests. For major versions we should …

dev: add dependabot to maintain deps

---

core/app/c/[communitySlug]/pubs/[pubId]/page.tsx
core/app/components/pubs/RemovePubButton.tsx
core/app/components/pubs/RemovePubForm.tsx
core/app/components/pubs/RemovePubFormClient.tsx
core/playwright/pub.spec.ts

Can't remove pub from pub page, only from Pub list or stages page.
Just add the `PubRemoveButton` to `/c/[communitySlug]/pubs/[pubId]`
1. Create new Pub
2. Go to Pub page
3. Press remove button

feat: add remove button to pub page

---

core/next.config.mjs

Next builds are long.
TLDR: total CI time decrease for building core is 1m30s!! very nice
Enables `experimental.parallelServerBulldTraces` in `next.config.mjs`. This makes the tracing of server routes take place in a separate worker, which slightly decreases build times (ideally).
As you can see below, this results in ~50s or roughly 19% faster `next build`s! Seems great for doing literally nothing.  
Additionally, I disable webpack caching in line with [this next recommendation](https://nextjs.org/docs/app/building-your-application/optimizing/memory-usage#disable-webpack-cache). Currently serializing and writing the webpack cache takes a long time, we even get this warning often
```
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (243kiB) impacts deserialization …
```

dev: set some next settings to improve build times

---

core/actions/googleDriveImport/run.ts
core/prisma/exampleCommunitySeeds/arcadiaJournal.ts

n/a
1. Creates a seed file that can be used to test a journal community locally more easily.
2. Fixes a sorting bug that was causing duplicate versions to be created even when no content had changed
3. Updates the import action to update legacy pubs when they change, allowing us to 
1. Import a gdrive doc from scratch and make sure the expected number of versions are created.
2. Re-run the gdrive import without modifying anything and make sure no versions are created and no old versions are modified
3. Update the head (_Name) gdoc, run the gdrive import, and make sure a new version is created and no old version's html are modified
4. Re-run the gdrive import without modifying anything and make sure no new version is created and no old version's html are modified
5. Make a modification to …

GoogleImportAction: Update legacy versions

---

.github/workflows/on_pr.yml
docker-compose.preview.yml
self-host/docker-compose.yml

This PR temporarily disables the minio-init service, which variably returns status code 0 or 1. I'm not sure what the cause is yet, but since file uploads are not working, I'm going to go ahead and merge this to get the preview workflow to report successes.

chore: PR preview fixes

---

core/lib/server/assets.db.test.ts
core/package.json
pnpm-lock.yaml

- **fix: update aws sdk version to unbreak large file uploads**
- **dev: add tests with large file**
`uploadFileToS3` would fail if filesize > 5mb
Version mismatch with s3 client and the multipart fileupload helper library. 
Since they introduced this change (https://github.com/aws/aws-sdk-js-v3/issues/6810), it would try to access a checksum method which did not yet exist.
1. Run tests.
2. See that the test fails on the previous version. ie, in `core`, do `pnpm i @aws-sdk/client-s3@3.645.0` and do `pnpm vitest lib/server/assets.db.test.ts`

fix: allow file-uploads from the server > 5mb

---

packages/context-editor/src/commands/horizontal.ts
packages/context-editor/src/components/MenuBar.tsx
packages/context-editor/src/schemas/horizontal.ts
packages/context-editor/src/schemas/index.ts
packages/context-editor/src/style.css

Closes https://github.com/pubpub/platform/issues/949
Adds horizontal rule button!
Run storybook in the context-editor package and try using the horizontal rule button.
https://github.com/user-attachments/assets/04822340-ed56-43d4-8c1e-6904c1561669
At first I thought maybe the `<hr/>` should be inserted _after_ the current node, but it looks like legacy inserts it at the cursor so I kept it that way

Horizontal rule

---

core/actions/googleDriveImport/discussionSchema.ts
core/actions/googleDriveImport/formatDriveData.ts

This resolves the 11 pubs that failed to convert actions originally during live testing.

Update Google Action handling of discussions

---

core/app/components/FormBuilder/ElementPanel/SelectElement.tsx

If you deleted all the elements from a form, it was impossible to add new elements to the form. The bug was easy to miss/rarely happens because we always create forms with some default fields.
https://kfg.sentry.io/issues/6368052103/?referrer=github-pr-bot
- Open (or create) a form in the preview app 
- Delete every element
- Save the form
- Add a new element back to the form (it shouldn't crash)

Allow adding elements to an empty form

---

core/kysely/database-init.ts
core/kysely/database.ts
core/kysely/scripts/migrate-hierarchy.ts

Partial #952 
This PR just moves the instantiation of our Kysely instance into a factory function so we can create instances of Kysely in an env-independent way.
Quick smoke test should do the trick!

refactor: move db creation to factory fn for env-independent instances

---

core/app/c/[communitySlug]/pubs/[pubId]/page.tsx

Removes the "Pub Contents" header from pub pages

Remove leftover children heading on pub details page

---

pnpm-lock.yaml
pnpm-workspace.yaml

There was a Next CVE that's fixed in the 15.2.3 (https://nextjs.org/blog/cve-2025-29927)
while technically not impacting us as we don't do auth in middleware, probably still good to update.

fix: update next to fix CVE

---

core/app/components/forms/types.ts
core/app/components/pubs/PubEditor/PubEditor.tsx
core/app/components/pubs/PubEditor/PubEditorClient.tsx

Resolves #1041
This PR renders a form's submit buttons on the pub update/edit page when the logged in user is a pub contributor.
In addition the PR hides the stage select dropdown on the pub update/edit page when the logged-in user does not have `movePub` capability.
1. Add a submit button to the default form of an existing pub type in any community. Configure the submit button with a stage to move into when clicked.
2. Create a pub of this pub type using the create pub button on either the pub/workflows pages or the stage editor panel.
3. Submit the form using the normal Save button. You should see the pub has no stage (or the stage you selected in the form).
4. Submit the form using the new submit button you added to the default form in step 1. You should see the pub now has the stage …

feat: render submit buttons on edit page

---

core/actions/googleDriveImport/formatDriveData.ts
core/actions/googleDriveImport/gdocPlugins.ts

This PR sets the stage for removing the majority of google doc processing (it will now instead be done as part of the frontend build process). The major change is updating the way we process/re-upload assets, since we're dealing with raw google doc tables now, instead of formatted HTML figure elements.
I'm pushing this up to main so I can do my test to compare that frontend HTML is identical after this refactor. If all works, there will be another commit and PR that removes the unnecessary code after it's been migrating to the frontend.

Simplify gaction processing

---

.github/workflows/pull-preview-script.sh
core/lib/env/flags.ts

N/A
Amends the PullPreview pre-script to also clean up unused/dangling docker images on each deploy.
Not sure... I think as long as the deployments no longer fail due to out-of-space errors we should be good to go!

chore: prune dangling docker images in preview environments

---

.github/workflows/pull-preview.yml

N/A
Configures PullPreview with our preview.pubpub.org custom domain.
TBD

chore: specify pullpreview custom domain

---

infrastructure/terraform/environments/stevie/main.tf

Output of `mask tf plan -n stevie`
```
Terraform will perform the following actions:
<= data "aws_ecs_task_definition" "this" {
+ arn                  = (known after apply)
+ arn_without_revision = (known after apply)
+ execution_role_arn   = (known after apply)
+ family               = (known after apply)
+ id                   = (known after apply)
+ network_mode         = (known after apply)
+ revision             = (known after apply)
+ status               = (known after apply)
+ task_definition      = "stevie-core"
+ task_role_arn        = (known after apply)
}
+/- resource "aws_ecs_task_definition" "this" {
~ arn                      = "arn:aws:ecs:us-east-1:246372085946:task-definition/stevie-core:229" -> (known after apply)
~ arn_without_revision     = …
```

fix: use prod datacite api url in production

---

core/app/components/pubs/PubEditor/actions.ts
core/lib/server/maybeWithTrx.ts
core/lib/server/pub-filters-validate.ts
core/lib/server/pub-op.db.test.ts
core/lib/server/pub-op.ts
core/lib/server/pub.ts
core/lib/server/pubFields.ts

-
The goal is to split off some work from the migrations pr to make it more reviewable in the long term.
This PR does two things that are necessary for #1171 
1. Allow batch updating/creating/upserting of pubs. that way in order to create N pubs, rather than needing `N x M` calls to the db, where `M` is the number of calls pubop makes for creating one pub, we now only need `M` calls. Much more efficient.
2. Fix and expand the `byValue` pattern established by `PubOp.upsertByValue` and `PubOp.updateByValue` to actually work, and also be available for `relateByValue`. This allows you to do `pubOp`s of which you may only know a specific value (in the case of the migration the `legacy-id`), rather than the id. This is very useful for doing imports.
- Convince yourself of the tests
- See for …

feat: add batch operations to PubOp, expand/fix *byValue capabilities

---

core/app/components/forms/types.ts
core/app/components/pubs/PubEditor/PubEditor.tsx
core/app/components/pubs/PubEditor/PubEditorClient.tsx
core/lib/pubs.ts

Fixes #1128
Well, it was already fixed, but this change fixes missing title/name for pubs that contributor members are not authorized to see.
This PR updates the `PubEditor` to not consider the user when fetching the pub and its pub values. This means that related pubs are completely fetched, ensuring they have a title.
Pub values not in the form are hidden unless the user can `seeExtraPubValues` .
Make sure you are unable to reproduce the issue reported in #1128.

fix: fetch related pub values in form regardless of membership role

---

infrastructure/terraform/environments/blake/main.tf
infrastructure/terraform/environments/cloudflare/main.tf

Removes our unused and broken staging env at https://blake.duqduq.org to save money. After this is applied we can fully delete that directory if we want.
The terraform plan for the blake env is too big to go in a github comment so it's in this gist. https://gist.github.com/kalilsn/95cdff2371c2260060faee98f8406c38
<details>
<summary>Terraform plan for cloudflare env</summary>
```
Terraform will perform the following actions:
- resource "cloudflare_record" "ns" {
- allow_overwrite = false -> null
- created_on      = "2024-05-02T20:32:27.37627Z" -> null
- hostname        = "blake.duqduq.org" -> null
- id              = "10ac0f190eb92c51b239fde326777828" -> null
- metadata        = {} -> null
- modified_on     = "2024-05-02T20:32:27.37627Z" -> null
- name            = "blake.duqduq.org" -> …
```

Remove blake deployment

---

core/package.json

Resolves #1233 
After #1131 we no longer cache data on the filesystem, and instead store it in redis. In both local development and in the sandbox deployments, we regularly run the reset command, which also attempts to clear the cache. Since that cache-clearing function wasn't working, we could end up with stale data in the sandbox cache.
It's easiest to see this clear the cache if you install redis-cli (or some kind of gui redis app). `redis-cli` monitor will let you see commands as they come in, and `redis cli scan 100` will print 100 keys so you can see if there's data in the cache.
- With the valkey cache running (`pnpm -w dev:cache:start`) and after using the app a bit, run `redis cli scan 100` to show there's data in the cache
- Optionally, run `redis-cli monitor` in a separate …

Fix clear cache to clear valkey instead of filesystem cache

---

core/actions/datacite/run.ts

N/A
This PR simply removes some unused, and maybe unuseful properties from the value returned from the DataCite action upon successful deposit. This should make the DataCite action `action_runs` rows fit into the 8kb payload limit enforced by `pg_notify` for our pseudo-real-time updates.
N/A

trim datacite result to avoid 8kb pg_notify payload violation

---

core/app/components/MemberSelect/MemberSelectClient.tsx
core/playwright/actions.config.spec.ts
packages/db/src/public/PublicSchema.ts
packages/ui/src/autocomplete.tsx

Closes https://github.com/pubpub/platform/issues/1235
Configures the member select/autocomplete components so that you can clear their value, either by erasing its contents, or by clicking the 'x' button
1. Visit http://localhost:3000/c/starter/stages/manage and click on a stage that has an email action (i.e. "Draft"). Or, in the preview environment, go to https://pr-1263-email-action-rec-ip-3-91-78-129.my.preview.run/c/starter/stages/manage?editingStageId=10d974ae-345f-4021-9ca2-e47f15b6b98b
3. Add a recipient member to an action email
4. Save ("Update config" button)
5. Refresh the page
6. Clear the member field by erasing its contents
7. Save 
8. Refresh the page-there should be no member saved
Repeat the steps above, but instead of clearing by erasing its contents, clear by clicking …

Deleting email recipient

---

core/app/c/[communitySlug]/ContentLayout.tsx
core/app/c/[communitySlug]/pubs/PubList.tsx
core/app/c/[communitySlug]/pubs/PubSearchInput.tsx
core/app/c/[communitySlug]/pubs/PubSelector.tsx
core/app/c/[communitySlug]/pubs/page.tsx
core/app/c/[communitySlug]/stages/components/StageList.tsx
core/app/components/DataTable/PubsDataTable/validations.ts
core/app/components/Pagination.tsx
core/app/components/PathAwareDialog.tsx
core/app/components/PubCard.tsx
core/app/components/SearchDialog.tsx
core/app/components/pubs/CreatePubButton.tsx
core/app/layout.tsx
core/lib/authentication/loginData.ts
core/lib/authentication/lucia.ts
core/lib/server/pub.fts.db.test.ts
core/lib/server/pub.ts
core/lib/server/stages.ts
core/stories/PubCard.stories.tsx
packages/contracts/src/resources/site.ts
packages/ui/src/hooks/index.ts
packages/ui/src/hooks/useKeyBoardShortcut.tsx
packages/ui/src/hooks/usePlatform.tsx
packages/ui/src/sidebar.tsx

Resolves #1197 
Adds search capabilities to `getPubsWithRelatedValues` and adds a searching filter to `/pubs`.
Not done:
Video overview (kinda rambly sorry)
https://github.com/user-attachments/assets/0b75eb3b-638d-4aa1-a32d-46d6fff29cf6
1. go to legacy/pubs
2. search some stuff
3. page through the results if possible
When searching
Changed the pagination a bit when searching, as i didn't want to find out how many results there are in total (that's kinda costly), so I just get `N = perPage + 1` items, check if `N > perPage`, if so i allow the user to paginate to the next page.
There's an argument to make to just remove pagination for searching entirely, and only show the first ~25 results, and the user just needs to provide a better query if they aint happy.

feat: search on all pub page

---

core/lib/server/render/pub/renderMarkdownWithPub.ts

Resolves #1299
Adds a new `fallback` attribute to the `:value` directive so emails can still be sent for pubs with optional/missing field values.
1. Run the email action with a template containing a value directive for a value that doesn't exist. Specify a fallback attribute, e.g. `:value{field="pubpub:nonsense" fallback="(No value was present)"}`.
2. The sent email should render "(No value was present)" instead of failing to send.

feat: add fallback attribute to value directive

---

site-builder/src/lib/env/server.ts

N/A
Quick fix to make the site builder's `S3_ENDPOINT` env var optional.

fix: make s3 endpoint optional as described in the terraform config
