pubpub/platform

core/app/c/[communitySlug]/stages/page.tsx
Closes #630
1. Go to `/croccroc/stages`
2. Try to create a Pub in a stage you can see
3. See that it shows up
=> feat: add pub create button to workflows page

core/app/api/v0/c/[communitySlug]/site/[...ts-rest]/route.ts, core/lib/authorization/capabilities.ts, packages/contracts/src/resources/site.ts
Resolves #740 
This PR adds the ability to authenticate API calls using the `userCan` function.
=> feat: add permission authentication to api

core/app/c/[communitySlug]/pubs/PubList.tsx
Very simply just changes the page size for the all pubs page to 10.
Trust me
=> fix: change page size to 10

core/app/api/v0/c/[communitySlug]/site/[...ts-rest]/route.ts, core/app/c/[communitySlug]/members/page.tsx, core/app/c/[communitySlug]/pubs/PubList.tsx, core/app/c/[communitySlug]/pubs/[pubId]/page.tsx, core/app/c/[communitySlug]/pubs/page.tsx, core/app/c/[communitySlug]/settings/tokens/page.tsx, core/app/c/[communitySlug]/stages/[slug]/page.tsx, core/app/c/[communitySlug]/stages/[stageId]/page.tsx, core/app/c/[communitySlug]/stages/components/Assign.tsx, core/app/c/[communitySlug]/stages/components/Move.tsx, core/app/c/[communitySlug]/stages/components/StageList.tsx, core/app/c/[communitySlug]/stages/components/StagePubActions.tsx, core/app/c/[communitySlug]/stages/manage/StagesContext.tsx, core/app/c/[communitySlug]/stages/manage/actions.ts, core/app/c/[communitySlug]/stages/manage/components/editor/StageEditor.tsx, core/app/c/[communitySlug]/stages/manage/components/editor/StageEditorContext.tsx, core/app/c/[communitySlug]/stages/manage/components/panel/StagePanelOverview.tsx, core/app/c/[communitySlug]/stages/manage/components/panel/StagePanelOverviewManagement.tsx, core/app/c/[communitySlug]/stages/manage/page.tsx, core/app/c/[communitySlug]/stages/page.tsx, core/app/components/PubRow.tsx, core/lib/server/stages.ts, core/lib/stages.ts, core/playwright/fixtures/pubs-page.ts, core/playwright/fixtures/stages-manage-page.ts
#800 
#799 
This PR adds a new page for viewing pubs in an individual stage, and limits the number of stages shown on the all stages page so that it loads faster. Refactoring the stages components to make this possible led me to make a few modifications to the stages query so that it returns the move constraint destinations and sources with exactly the data they need. I also took the opportunity to remove the integration actions and the token generation from all the components I touched.
As Jill Admin, visit http://localhost:3000/c/arcadia-research/stages. The page should successfully load much faster than before (though still somewhat slow, since some of the pub_values queries still take 1-2s locally).
Make sure three pubs render per stage, the stage has the number of pubs in it, and …
=> Add individual stage page and limit number of pubs per stage

core/app/c/[communitySlug]/activity/actions/page.tsx
=> fix: actually fix the action run page

api.http.h, infrastructure/terraform.tfstate
=> remove some mistakenly added files

infrastructure/terraform/modules/core-services/main.tf
File upload wasn't working anymore because we didn't have the right S3 cors configuration.
=> Update bucket cors config

core/app/c/[communitySlug]/activity/actions/ActionRunsTable.tsx, core/app/c/[communitySlug]/activity/actions/getActionRunsTableColumns.tsx, core/app/c/[communitySlug]/activity/actions/page.tsx
Resolves #884 
Run an action, visit the action run page, try clicking on a pub title!
=> Add link to pub from action run log table

core/actions/googleDriveImport/formatDriveData.ts, core/actions/googleDriveImport/gdocPlugins.test.ts, core/actions/googleDriveImport/gdocPlugins.ts, core/actions/googleDriveImport/getGDriveFiles.ts, core/actions/googleDriveImport/run.ts
This adds:
- Better support for [10.abc] style references
- Asset re-uploading
- A couple other small fixes.
=> Google Action Updates

.github/workflows/on_pr.yml, .github/workflows/pull-preview.yml
CI would not run on PR open, and preview would not deploy on adding label
1. See that CI immediately ran on PR open
2. Add preview label, observe that the necessary actions spin up
=> fix: run ci correctly on pr

.github/workflows/on_main.yml, .github/workflows/pull-preview.yml, core/playwright.config.ts
Resolves #1012 
This PR enables pullpreview deployments on the `main` branch.
I think I'm going to just merge this and see what happens.
=> Sandbox environment

packages/context-editor/package.json, packages/context-editor/playwright/blocks.spec.ts, packages/context-editor/playwright/utils.ts, packages/context-editor/src/commands/blocks.ts, packages/context-editor/src/components/MenuBar.tsx, packages/context-editor/src/plugins/index.ts, packages/context-editor/src/plugins/inputRules.ts, packages/context-editor/src/plugins/keymap.ts, packages/context-editor/src/schemas/index.ts, packages/context-editor/src/schemas/list.ts, packages/context-editor/src/style.css, pnpm-lock.yaml
Closes https://github.com/pubpub/platform/issues/945
Adds lists, both bullet and ordered, to the editor.
I set up a form with a rich text editor in the preview environment here to play with: https://pr-1082-editor-lists-ip-3-80-61-184.my.preview.run/c/croccroc/public/forms/editor-default-editor/fill
https://github.com/user-attachments/assets/5ca02bb1-1741-4302-8a35-235c644f5c85
Because of the way we have a button to open the AttributePanel for each block, the bullet points end up being spaced pretty far apart. 
And sublists have their bullets kind of hidden among the borders. I tried to move the bullet markers 'into' the list item, but this caused other formatting issues I haven't been able to quite figure out yet. But if we know we want these to look a certain way, I'll give it another …
=> Lists in editor

core/next.config.mjs, pnpm-lock.yaml, pnpm-workspace.yaml
- **chore: upgrade sentry**
- **fix: set cacheMaxMemSize 0**
App crash sometimes
https://knowledgefutures.slack.com/archives/CMAQM0BNV/p1743537155616299
Send it. Ideally run some big queries again and see if we live
=> fix: fix memory leak by upgrading sentry

packages/context-editor/playwright/marks.spec.ts, packages/context-editor/src/commands/marks.ts, packages/context-editor/src/components/MenuBar.tsx, packages/context-editor/src/schemas/index.ts, packages/context-editor/src/schemas/subSuperScript.ts, packages/context-editor/src/schemas/underline.ts, packages/context-editor/src/style.css
Closes https://github.com/pubpub/platform/issues/947
Closes https://github.com/pubpub/platform/issues/943
Implements subscript, superscript, and underline in the editor.
Try the editor out! https://pr-1144-sub-superscript-ip-3-85-203-222.my.preview.run/c/croccroc/public/forms/review/fill
=> Editor: sub and superscript, + underline

.github/workflows/on_main.yml, .github/workflows/on_pr.yml, .github/workflows/pull-preview.yml
Updating the on_main and on_pr workflows to configure the caddyfile appropriately
=> fix: use sandbox.pubpub.org for sandbox preview url

.github/workflows/on_main.yml, .github/workflows/on_pr.yml, .github/workflows/pull-preview.yml, docker-compose.preview.pr.yml, docker-compose.preview.sandbox.yml, docker-compose.preview.yml
Gonna wait to merge this until later this evening. But this cleans up the squirrely variable substitution with the help of a couple new compose files, and also fixes a bug where sometimes you can get redirected to `localhost:3000` in the sandbox.
=> chore: use compose file merging

README.md
Updated the readme with self-hosting guidance.
=> make a few readme edits

core/lib/server/pub.ts
=> fix: run all update queries in transaction

core/playwright/fixtures/member-page.ts, core/playwright/invites.spec.ts
The last commit to #1155 skipped the tests in [its ci run](https://github.com/pubpub/platform/actions/runs/14863394406?pr=1155), which caused my automerge to merge broken tests to main. These tests passed locally, so I just assumed the success meant they passed in ci too.
This PR should fix those failing tests.
=> Fix test errors on main

core/actions/_lib/runActionInstance.ts, core/actions/datacite/run.test.ts, core/actions/log/run.ts, core/actions/types.ts, core/app/api/v0/c/[communitySlug]/sse/route.ts, core/app/c/[communitySlug]/layout.tsx, core/app/c/[communitySlug]/stages/manage/components/panel/StagePanelSheet.tsx, core/app/c/[communitySlug]/stages/manage/components/panel/actionsTab/StagePanelActionEditor.tsx, core/app/c/[communitySlug]/stages/manage/page.tsx, core/app/components/ActionUI/ActionRunForm.tsx, core/kysely/database-init.ts, core/kysely/database.ts, core/lib/db/queries.ts, core/lib/notify/SSERevalidator.tsx, core/lib/notify/useSSEUpdates.ts, core/package.json, core/playwright/actions.sse.spec.ts, core/prisma/migrations/20250415174821_notify_change/migration.sql, pnpm-lock.yaml
This reverts commit 15a7ca1fd300b61332185b4e5eb5eb59edde7e45.
=> Reapply "feat: dead simple realtime update framework (#1175)" (#1223)

core/actions/_lib/runActionInstance.ts, core/actions/datacite/run.test.ts, core/actions/datacite/run.ts
=> More datacite/action logs

core/app/api/v0/c/[communitySlug]/sse/route.ts
PubPub crashing after doing a bunch of actions in `/stages/manage`.
Connections during SSE were not cleaned up properly in a timely manner, which, when doing a bunch of actions on pages with `SSE`, caused a bunch of connections to stay idle for no reason.
I did a better job of releasing the clients (not using async `forEach` for one...), unlistening the proper channel, and added some error logging so it's easier to figure out what went wrong in the future.
- Add this
```ts
setInterval(() => {
logger.info({
msg: "pool stats",
stats: {
total: pool.totalCount,
idle: pool.idleCount,
waiting: pool.waitingCount,
},
});
}, 10_000);
```
After here:
https://github.com/pubpub/platform/blob/2d71267a712a9085e55e2a31c4469bef79f970d3/core/kysely/database-init.ts#L33-L38
- Go to `/stages/manage`
- …
=> fix: cleanup connections properly

core/app/c/(public)/[communitySlug]/public/forms/[formSlug]/fill/ExternalFormWrapper.tsx, core/app/c/(public)/[communitySlug]/public/forms/[formSlug]/fill/page.tsx, core/app/c/[communitySlug]/pubs/[pubId]/edit/page.tsx, core/app/c/[communitySlug]/pubs/[pubId]/page.tsx, core/app/c/[communitySlug]/pubs/create/page.tsx, core/app/components/pubs/InitialCreatePubForm.tsx, core/app/components/pubs/PubEditor/PubEditor.tsx, core/app/components/pubs/PubEditor/PubEditorClient.tsx, core/app/components/pubs/PubEditor/PubEditorWrapper.tsx, core/app/components/pubs/PubEditor/actions.ts, core/lib/server/form-access.ts, core/lib/server/navigation/redirects.ts, core/playwright/fileUpload.spec.ts
Reworked the logic of `PubEditor.tsx` a bit, as it was very hard to follow and quite inefficient.
Also changed the redirection logic of forms slightly.
1. Observe that tests pass
2. Be happy
=> refactor: clean up pubeditor logic

core/actions/buildJournalSite/action.ts, core/actions/buildJournalSite/run.tsx, core/app/(user)/communities/CommunityTable.tsx, core/app/api/v0/c/[communitySlug]/site/[...ts-rest]/route.ts, core/app/c/[communitySlug]/settings/legacy-migration/MigrationForm.tsx, core/lib/server/apiAccessTokens.ts, core/lib/server/legacy-migration/legacy-migration.ts, core/prisma/seeds/blank.ts, docker-compose.preview.yml, site-builder/.env.development, site-builder/.env.server.development, site-builder/docker-compose.yml, site-builder/package.json, site-builder/src/pages/[slug].astro, site-builder/src/pages/index.astro, site-builder/tailwind.config.mjs
Fixes a bunch of errors that were preventing you from building a site.
- `blank` didn't have a token
- API tacitly assumes that every request has a user, leading to errors
- Some errors in the sitebuilder itself still relying on the community being called `starter` (omg)
=> fix: make site building work again + fix some sandbox issues
